[workspace]
members = ["crates/libs/*", "crates/bins/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.92.0"
description = """
daoyi-vue-rs
"""
license = "MIT"
authors = ["Gemiman <<gemiman@vip.qq.com>>"]
readme = "README.md"

[workspace.dependencies]
axum = "0.8.7"
tokio = { version = "1.48.0", features = ["full"] }

[package]
name = "daoyi-vue-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
