name: app
active_profile: dev
server:
  port: 3001
  timeout: 120s
  max_body_size: 11m
  max_age: 12h
log:
  level: info
  dir: ./logs
  filename: app.log
  rolling: daily
database:
  driver: postgres
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: 1234567
  database: postgres
  schema: public
jwt:
  secret: 1234567890
  expire: 3600s
  audience: audience
  issuer: issuer
auth:
  ignored_urls:
    - /
    - "**/login"
    - /admin-api/system/oauth2/check-token
  tenant_ignored_urls:
    - /
    - /admin-api/system/oauth2/check-token
  header_key_token: Authorization
  header_key_tenant: tenant-id
  token_expiration: 100000h
  token_check_url: http://127.0.0.1:48001/admin-api/system/oauth2/check-token
  tenant_check_url: http://127.0.0.1:48001/admin-api/system/tenant/check-token
redis:
  host: localhost
  port: 6379
  password: 123456789
  database: 0
  expire_seconds: 60
nacos:
  enabled: false
  server_addr: 127.0.0.1:8848
  namespace: public
  app_name: app
  group: DEFAULT_GROUP
  auth_username: nacos
  auth_password: nacos